### ISSUE TITLE
Problem debugging dos code

### ISSUE THREAD

**Issue by slo** [ThomasJaeger/VisualMASM#2]
Hi,
My instance of visual MASM produces following output (for dos 16bit exe)when I try to debug code:
`Assembling G:\masm32\projs\`
`Microsoft (R) Macro Assembler Version 6.14.8444`
`Copyright (C) Microsoft Corp 1981-1997.  All rights reserved.`
``
``
` "G:\masm32\bin\ml.exe /Zi /Zd /Zf" /c /Fo"G:\masm32\projs\Debug\Assembly1.obj" G:\masm32\projs\ASSEMB~1.ASM`
`MASM : warning A4018: invalid command-line option : /Z /c /FoG:\masm32\projs\Debug\`
`MASM : warning A4018: invalid command-line option : /Z/c /FoG:\masm32\projs\Debug\`
`MASM : warning A4018: invalid command-line option : /Zc /FoG:\masm32\projs\Debug\`
and so on.

Problem seems to lie on " character after /Zf

From my investigation this is due to line from uDM.pas[2340]:
`ptDos16EXE: cmdLine := ' "'+FVisualMASMOptions.ML32.FoundFileName+debugOption+'" /c /Fo'+pf.OutputFile+
      ' '+ExtractShortPathName(pf.FileName); `
Maybe `debugOption` should be excluded from double quotes ?

**Comment by ThomasJaeger** [comment]
Thanks a lot for pointing this out.  I will fix this as soon as I can.  Thanks again for your feedback.  I appreciate it.

**Comment by ThomasJaeger** [comment]
I fixed it. Please try the latest version. Let me know if you still have any issues, please.

**Comment by slo** [comment]
Now, it works :)
Executable runs under Dosbox.
Thanks!

**Comment by ThomasJaeger** [comment]
Great, glad it's working now.

**Comment by ronny332** [comment]
Hi,
it looks like a similar issue still exists in the current version. I just tried to move an existing small assembly program over to visual masm and the output indicates that again the quotes are at the wrong place:

```
"c:\masm32\bin\ml.exe /Zi /Zd /Zf" /Fo"C:\Users\noname\Documents\Visual MASM\Test-01\Debug\Assembly1.obj" /c /AT /nologo "C:\Users\noname\Documents\Visual MASM\Test-01\Assembly1.asm
```

Without any quotes around the ml.exe and an extra space ight after the /Fo switch it is running smoothly:
```
c:\masm32\bin\ml.exe /Zi /Zd /Zf /Fo "C:\Users\noname\Documents\Visual MASM\Test-01\Debug\Assembly1.obj" /c /AT /nologo "C:\Users\noname\Documents\Visual MASM\Test-01\Assembly1.asm
```

The way these query strings get built is not configurable from the users side, right?
